### ISSUE TITLE
Build fails with 'A problem occurred evaluating project ':library'. > Could not find method bootJar()'

### ISSUE THREAD

**Issue by mryanprice** [spring-guides/gs-multi-module#10]
When I try to build the code in the "complete" directory, it fails with

```
A problem occurred evaluating project ':library'.
> Could not find method bootJar()
```

I get the same error on a fresh VM.  Looks like the [CI build failed with the same error](https://travis-ci.org/spring-guides/gs-multi-module/builds/395169954?utm_source=github_status&utm_medium=notification) as well.

**Comment by mryanprice** [comment]
Looks like you can fix it by just removing the `bootJar` section from `library/build.gradle`

**Comment by hukadev** [comment]
Hi @mryanprice 

This issue come from this PR.
https://github.com/spring-guides/gs-multi-module/commit/a4606ee679d367df2d3bf5812cdd96e86750c8ad

You could change to "jar" to avoid this issue.

Regards,
Huka
