### ISSUE TITLE
Cannot build multiple module project with spring data jpa.

### ISSUE THREAD

**Issue by DevDengChao** [spring-guides/gs-multi-module#11]
I just created a sample project shows the problem. (https://github.com/XieEDeHeiShou/Spring-multipe-module-project-sample)

The 'app' dependent on 'lib'. 
In 'lib/test/java/sample/dengchao/lib/LibServiceTest', `LibService` call `LibRepository` to find a `LibEntity` with id '1'. The test passed.

In 'app/main/java/sample/dengchao/app/Main', it test the same thing, but failed because of 
> Parameter 0 of constructor in sample.dengchao.lib.LibService required a bean of type 'sample.dengchao.lib.LibRepository' that could not be found.

**Comment by liuyukuai** [comment]
@XieEDeHeiShou 你这个问题解决了么

**Comment by dsyer** [comment]
This isn't really a question about the code in this repo. Please put usage questions on StackOverflow (feel free to link back to here).
