### ISSUE TITLE
Unable to execute mvn spring-boot:run 

### ISSUE THREAD

**Issue by zeno-ce** [spring-guides/gs-multi-module#20]
It's not possible to run the complete project from the command line using spring-boot:run.   
`mvn spring-boot:run -pl 'com.example:gs-multi-module-application' -am`

Results in the following error: 

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for gs-multi-module-library 0.0.1-SNAPSHOT:
[INFO] 
[INFO] gs-multi-module-library ............................ FAILURE [  2.948 s]
[INFO] gs-multi-module-application ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.510 s
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.4.RELEASE:run (default-cli) on project gs-multi-module-library: Unable to find a suitable main class, please add a 'mainClass' property
```

Jdk version:
openjdk version "1.8.0_191"

Jre version:
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)

Any help is greatly appreciated.

**Comment by dsyer** [comment]
The artifact id is `multi-module-application`, so you need to fix that. Works for me, but you also have to install the library (so `mvn install`) first, if you use the `-pl` option, and remove the `-am` options. Also `-pl application` works (which is what is in the guide text).
