### ISSUE TITLE
404 Not Found: Requested route ('spring.io') does not exist

### ISSUE THREAD

**Issue by lingocoder** [spring-guides/gs-multi-module#21]
The [*Creating a Multi Module Project*](https://spring.io/guides/gs/multi-module/) guide does not exist at spring.io anymore.

Attempting to access it at spring.io, results in a „*`404 Not Found: Requested route ('spring.io') does not exist`*“ error:

![spring guides issue 101 0](https://user-images.githubusercontent.com/49788472/58590132-eefd0800-8252-11e9-84ae-6168c7ca5cd2.png)

**Comment by dsyer** [comment]
Works for me. Must have been a glitch.
