### ISSUE TITLE
The configuration used in this guide will not find repositories and entities defined in the library module

### ISSUE THREAD

**Issue by behrangsa** [spring-guides/gs-multi-module#23]
The current setup will not find JPA entities and repositories defined in the library module, but this paragraph gives the impression that it will:

> Because `DemoApplication` is inside a different package (`hello.app`) than `MyService` (`hello.service`), `@SpringBootApplication` won't detect it initially. There are different ways to allow `MyService to be picked up:
> 
> * Import it directly with `@Import(MyService.class)`.
> * Fetch everything from it's package using `@SpringBootApplication(scanBasePackageClasses={...})`.
> * The method this guide uses--specifying the parent package by name, `hello`.

But if in the shared lib, we have entity classes defined under `hello.entity` and repositories under `hello.repository`, `@SpringBootApplication(scanBasePackages = "hello")` won't pick them up.

To make the app module pickup the entity and repository types, either `DemoApplication` should be defined in the `hello` package (as opposed to `hello.app`) or it is should be annotated with `@EntityScan("hello.entity")` and `@EnableJpaRepositories("hello.repository")`.

**Comment by dsyer** [comment]
This project does not use JPA though, so wouldn't it complicate matters to discuss it directly. Maybe a footnote would help? In any case I'm not sure I understand the point (since `hello.entity` will definitely be picked up by a scan of `hello`).

**Comment by behrangsa** [comment]
> In any case I'm not sure I understand the point (since hello.entity will definitely be picked up by a scan of hello).

It will get component scanned but it will not get entity scanned. I will upload an example tomorrow. 🙂

**Comment by behrangsa** [comment]
I have attached two examples that show this problem. I might have time to fork the current guide and add some extra details next month.

Just to recap:

### Without an explicit `@EntityScan`, the app crashes at runtime with error

> Caused by: java.lang.IllegalArgumentException: Not a managed type: class com.example.utils.entity.Message

### Without an explicit `@EnableJpaRepositories`, the app crashes at runtime with error: 

> NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.utils.repository.MessageRepository' available: expected at least 1 bean which qualifies as autowire candidate.

---

* [ExtraAnnotations.zip](https://github.com/spring-guides/gs-multi-module/files/3362968/ExtraAnnotations.zip)
* [OnlySpringBootApplication.zip](https://github.com/spring-guides/gs-multi-module/files/3362969/OnlySpringBootApplication.zip)

**Comment by dsyer** [comment]
OK, I see. Your sample apps have `@SpringBootApplication` on a class in `com.example.app` which is *not* a parent of the entity and repository packages (like in your description above). Spring Boot doesn't automatically apply the `basePackages=` from `@SpringBootApplication` to its `@EntityScan` and `@EnableJpaRepositories`.

I'm still not convinced we need to mention it here (there is no JPA), but maybe it wouldn't hurt to just add a quick sidebar or something. Also you could raise an issue in Spring Boot if you find this behaviour surprising.
