### ISSUE TITLE
Invalid pointer to library version

### ISSUE THREAD

**Issue by mhewedy** [spring-guides/gs-multi-module#43]
https://github.com/spring-guides/gs-multi-module/blob/4664a5982df3f24c0fca58b3640970a29ee0f66d/complete/application/pom.xml#L31

the `${project.version}` will always point to the application project version regardless of the library project version.

which makes the application point to an old library version (in case of library version changed in future).

**Comment by dsyer** [comment]
Why would the library version not change at the same time (that's why this is a "multi-module project")?

**Comment by mhewedy** [comment]
I agree, but if one does by mistake, it would be a horrible issue.
