### ISSUE TITLE
Maven build is not working.

### ISSUE THREAD

**Issue by ricardojlrufino** [spring-guides/gs-multi-module#45]
Running in (complete) folder:
./mvnw install && ./mvnw spring-boot:run -pl application

ERROR:
Failed to execute goal on project multi-module-application-complete: Could not resolve dependencies for project com.example:multi-module-application-complete:jar:0.0.1-SNAPSHOT: Could not find artifact com.example:library:jar:0.0.1-SNAPSHOT -> [Help 1]

![image](https://user-images.githubusercontent.com/515675/132559485-684757ac-3da6-440e-910e-3bddc2debdc2.png)

I'm using docker 
docker run -it --rm --name my-project -v "$(pwd)":/root -w /root adoptopenjdk/maven-openjdk11:latest mvn clean install

Its works with gradle:
./gradlew build && ./gradlew :application:bootRun

**Comment by ricardojlrufino** [comment]
Running in (initial) folder: is working.

**Comment by dsyer** [comment]
It works for me, even in docker per your example. Are you sure you are doing the same? Maybe something changed.

**Comment by ricardojlrufino** [comment]
You are running version in folder: complete ?

**Comment by dsyer** [comment]
Yes.

**Comment by aquariuslt** [comment]
> Yes.

You might manual update `complete/application/pom.xml`'s dependencies `com.example.library` to `com.library.library-complete`

**Comment by ricardojlrufino** [comment]
@aquariuslt i missed this... ;)
