### ISSUE TITLE
can a Gradle multi-project build be added to this guide? 

### ISSUE THREAD

**Issue by 62mkv** [spring-guides/gs-multi-module#49]
Hi all

Current "complete" folder does not have a `build.gradle` on "root" level, thus each project has to deal with dependencies completely autonomously

I would like to see more "conventional" multi-module (multi-project) Gradle build config, that would for example let me define shared ("allprojects") logic in the root `build.gradle` and then only add module-specific customizations in each module's `build.gradle` files?

Say, then the project structure could look like this:
```
root
|-app1
   |-build.gradle
|-app2
   |-build.gradle
|-lib
   |-build.gradle
build.gradle
settings.gradle
```

I am currently trying to structure such build based on suggestions from here https://stackoverflow.com/a/59435028/2583044 but I have some issues where dependencies are "not found" and it looks like gradle does not know which version to apply to them These dependencies  ARE in the `spring-boot-dependencies-2.4.0.pom`, like 

> Could not find org.springframework.boot:spring-boot-starter-test:.

**Comment by Buzzardo** [comment]
There is a build.gradle file.
