### ISSUE TITLE
Export and import jar file

### ISSUE THREAD

**Issue by jan-brinkmann** [spring-guides/gs-multi-module#52]
According to the description, the goal is to export (or create, respectively) a jar file from some library project and to import that jar file into some root project.

Unfortunately, the library sources are directly imported and no jar file is created.

I would appreciate if the import and export jar tasks can be added to the tutorial.

**Comment by Buzzardo** [comment]
We keep the guides as short as possible, to make them doable in 15 minutes. Also, that's outside the realm of spring.
