### ISSUE TITLE
Upgrade Spring Boot to the latest version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-multi-module#55]
Update the guide to use the most recent Spring Boot version.

To do so, change the Spring Boot version in:

initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml

**Comment by 0scvr** [comment]
I'll do this. Please assign me :)

**Comment by 0scvr** [comment]
Any reason my PR isn't getting merged ? Do I need to make some changes ?

**Comment by Buzzardo** [comment]
I don't get notified about PRs unless I get mentioned in them or get assigned as a reviewer.
