### ISSUE TITLE
Add license section in readme

### ISSUE THREAD

**Issue by dalvishruti14** [spring-guides/gs-multi-module#59]
Update the LICENSE section in the README file to enhance the presentation. To add license badge and update the text with a cleaner format, including a hyperlink to the LICENSE file.
I would like to work on this issue.

**Comment by snicoll** [comment]
Thanks for the suggestion but the README is the source of the published guide (see https://spring.io/guides/gs/multi-module/). As such, adding a badge isn't an option.
