### ISSUE TITLE
[Question] Is this only reusable for Spring boot applications?

### ISSUE THREAD

**Issue by GlennVanSchil** [spring-guides/gs-multi-module#6]
I'm currently writing a library as describe in the documentation so I can reuse it in my other Spring boot applications. I have some colleagues that might benefit from this library as well, but they're not always using Spring boot or even Spring. Can they also use this library?

**Comment by dsyer** [comment]
What "'library"? This is a guide (documentation, not a library) and it is about building multi-module Spring Boot applications. You could re-use the patterns for non-Spring Boot apps, but the build configuration in the samples uses Spring Boot plugins to build executable jars. I guess it's up to you if that counts as not using Spring Boot.

**Comment by GlennVanSchil** [comment]
> What library?

![selection_009](https://user-images.githubusercontent.com/3930037/34662378-6d664ef0-f450-11e7-9a34-4e5ad7796866.png)

>  This is a guide (documentation, not a library) and it is about building multi-module Spring Boot applications.

This I know, but I'm not writing the full application at the moment only the reusable "library" as in your documentation so I can use if for my future Spring boot applications

I was just asking when the reusable part of the code aka the library is build with spring boot (using the annotations etc.) can a regular Spring MVC or even a non Spring Maven Application (the project importing the library) also use my library? Because not all my colleagues use Spring boot.

**Comment by dsyer** [comment]
Ah. I see, I didn’t make the link. Then, I suppose the answer is “yes it is just a library”. So it can be shared with other apps including non-Boot ones. I’m not sure how to make that more obvious.

**Comment by GlennVanSchil** [comment]
@dsyer Ok I wasn't sure because of the properties. the guide does say

>You don’t have to do it this way: a library might just provide pure Java APIs, and no Spring features. In that case the application that consumes the library would need to provide the configuration itself.

But I wasn't sure if I had to add or remove something in order to allow non Spring implementors to use my library.

Thank you!

**Comment by gauravhb** [comment]
Hello Glenn,
How did you use this Springboot based library in regular Spring MVC or even non-spring application?
I have same usecase.

**Comment by GlennVanSchil** [comment]
Hye @gauravhb 

For a regular Spring MVC project you can just add your library to your POM file and use it as you normally would inside a Spring project (see the spring guide itself)

For non spring maven projects you can still add it to your pom but you won't be able to autowire your beans, instead you'll have to create them as `MyBean myBean = new MyBean();` 

For non maven projects you'll have to add the jar of your library to the classpath manually. Same for the `MyBean myBean = new MyBean();` 

I strongly recommend using constructor injection in your library so non spring users are forced to implement all the beans. 

for example


Your library code:
```
@Component
public class MyBean {
  private InnerBean innerBean;
  
  @Autowired
  public MyBean(InnerBean innerBean){
    this.innerBean = innerBean;
  }
}
```

Non spring implementors:
```
InnerBean innerBean = new InnerBean();
MyBean myBean = new MyBean(innerBean);
```
